language: python
python:
  - "3.6"
install:
  - sudo apt update
  - sudo apt install ffmpeg
  - pip install -e .
script:
  - pytest --cov-report=xml --cov=epi tests -W ignore::DeprecationWarning
env:
  - CODECOV_TOKEN="152934f4-bf87-4e13-9132-3303aed1646d"
after_success:
  - bash <(curl -s https://codecov.io/bash)

